export enum QueryActions {
  AUTH_GET_LOGGED = "AUTH/GET_LOGGED",
  AUTH_LOGIN = "AUTH/LOGIN",

  RECORD_GET_ALL = "RECORD/GET_ALL",
  RECORD_POST = "RECORD/POST",
  RECORD_DETAIL = "RECORD/DETAIL",
}
